const data = {
  result: [
    {
      song: 'Forever',
      'song-link': 'https://www.lyrics.com/lyric/4020/Alessi+Brothers/Forever',
      artist: 'Alessi Brothers',
      'artist-link': 'https://www.lyrics.com/artist/Alessi+Brothers/15353',
      album: 'Long Time Friends',
      'album-link': 'https://www.lyrics.com/album/28848/Long Time Friends',
    },
    {
      song: 'Forever',
      'song-link': 'https://www.lyrics.com/lyric/34777/The+Cure/Forever',
      artist: 'The Cure',
      'artist-link': 'https://www.lyrics.com/artist/The+Cure/4004',
      album: 'The Carnage Visors/Curiosity Anomalies',
      'album-link': 'https://www.lyrics.com/album/217284/The Carnage Visors/Curiosity Anomalies',
    },
    {
      song: 'Forever',
      'song-link': 'https://www.lyrics.com/lyric/160655/Y%26T/Forever',
      artist: 'Y&T',
      'artist-link': 'https://www.lyrics.com/artist/Y%26T/5887',
      album: "Best of '81 to '85",
      'album-link': "https://www.lyrics.com/album/22391/Best of '81 to '85",
    },
    {
      song: 'Forever',
      'song-link': 'https://www.lyrics.com/lyric/215168/Marvin+Gaye/Forever',
      artist: 'Marvin Gaye',
      'artist-link': 'https://www.lyrics.com/artist/Marvin+Gaye/4344',
      album: 'How Sweet It Is to Be Loved by You',
      'album-link': 'https://www.lyrics.com/album/8068/How Sweet It Is to Be Loved by You',
    },
    {
      song: 'Forever',
      'song-link': 'https://www.lyrics.com/lyric/419419/Marvin+Gaye/Forever',
      artist: 'Marvin Gaye',
      'artist-link': 'https://www.lyrics.com/artist/Marvin+Gaye/4344',
      album: "Marvin Gaye's Greatest Hits, Vol. 2",
      'album-link': "https://www.lyrics.com/album/8072/Marvin Gaye's Greatest Hits, Vol. 2",
    },
    {
      song: 'Forever',
      'song-link': 'https://www.lyrics.com/lyric/580688/The+Marvelettes/Forever',
      artist: 'The Marvelettes',
      'artist-link': 'https://www.lyrics.com/artist/The+Marvelettes/4851',
      album: '16 Original Big Hits, Vol. 3',
      'album-link': 'https://www.lyrics.com/album/65081/16 Original Big Hits, Vol. 3',
    },
    {
      song: 'Forever',
      'song-link': 'https://www.lyrics.com/lyric/712796/Orleans/Forever',
      artist: 'Orleans',
      'artist-link': 'https://www.lyrics.com/artist/Orleans/5077',
      album: 'Forever',
      'album-link': 'https://www.lyrics.com/album/46095/Forever',
    },
    {
      song: 'Forever',
      'song-link': 'https://www.lyrics.com/lyric/713464/Rex+Smith/Forever',
      artist: 'Rex Smith',
      'artist-link': 'https://www.lyrics.com/artist/Rex+Smith/20600',
      album: 'Forever, Rex Smith',
      'album-link': 'https://www.lyrics.com/album/68021/Forever, Rex Smith',
    },
    {
      song: 'Forever',
      'song-link': 'https://www.lyrics.com/lyric/716153/The+Marvelettes/Forever',
      artist: 'The Marvelettes',
      'artist-link': 'https://www.lyrics.com/artist/The+Marvelettes/4851',
      album: "Motown's Preferred Stock: Stock Option No. 1",
      'album-link': "https://www.lyrics.com/album/172624/Motown's Preferred Stock: Stock Option No. 1",
    },
    {
      song: 'Forever',
      'song-link': 'https://www.lyrics.com/lyric/773701/Marty+Willson-Piper/Forever',
      artist: 'Marty Willson-Piper',
      'artist-link': 'https://www.lyrics.com/artist/Marty+Willson-Piper/114681',
      album: 'Rhyme',
      'album-link': 'https://www.lyrics.com/album/21938/Rhyme',
    },
    {
      song: 'Forever',
      'song-link': 'https://www.lyrics.com/lyric/814157/Kenny+Loggins/Forever',
      artist: 'Kenny Loggins',
      'artist-link': 'https://www.lyrics.com/artist/Kenny+Loggins/4778',
      album: 'Vox Humana',
      'album-link': 'https://www.lyrics.com/album/11898/Vox Humana',
    },
    {
      song: 'Forever',
      'song-link': 'https://www.lyrics.com/lyric/854897/Forever',
      artist: 'Various Artists',
      'artist-link': {},
      album: 'Men Without Women',
      'album-link': 'https://www.lyrics.com/album/11833/Men Without Women',
    },
  ],
};

export default data;
